---
accesspoint_ap0_address_v4: "172.26.0.1"
accesspoint_ap0_prefix_v4: "24"
accesspoint_dhcp_range_v4: "172.26.0.10,172.26.0.199"

# No default for
# accesspoint_ap0_v6_ula_net_48 : must be set in host_vars
accesspoint_ap0_v6_local_64: ""
accesspoint_ap0_v6_host: "::1"
# The three above are used to generate
# * the IPv6 address of ap0: "fdxx:xxxx:xxxx::1/64"
# * and the IPv6 dhcp range: "fdxx:xxxx:xxxx::1:1,fdxx:xxxx:xxxx:::ffff:fffe"


accesspoint_channel: "11"
accesspoint_country_code: "CH"
accesspoint_ssid: "{{ ansible_hostname }}"
# No default for
#   accesspoint_wpa_passphrase : asked interactively at the beginning

accesspoint_firewall_music_ports:
  - '6600/tcp'
  - '8080/tcp'
  - '12345/tcp'
  - '5353/udp'

accesspoint_disable_docker_networking: true
accesspoint_trust_public_zone: false
